#!/bin/bash

source ~/command/common

# SERVER="120.25.96.74"
SERVER="192.168.1.126"

function genDistForProject() {
    pushd ../../${1}/project 1>/dev/null
    vim -e -s config.js -c ":%s/localhost/${SERVER}/" -c ":wq"
    npm run dist
    vim -e -s config.js -c ":%s/${SERVER}/localhost/" -c ":wq"
    pushd ../dist 1>/dev/null
    # tar zcvf ${2}.tar.gz app.js main.css package.json public
    # mv ${2}.tar.gz ../../server/tools/dist
    popd 1>/dev/null
    popd 1>/dev/null
}

function show_help()
{
    echo "xdist [-t[targets]]"
    echo ""
    echo "  -t [targets]:targets as follows:"
    echo "      a, s[a: admin, s: server]"
    echo "      uses: -t a+s"
    echo "      uses: -t all"
    echo ""
}

function main()
{
    local has_oper a s all targets
    has_oper=0; a=1; s=2; all=3;
    while getopts :t: opt;do
        has_oper=1
        case $opt in
            t)targets=$(($OPTARG));;
            *)show_help;exit;;
        esac
    done
    [ $has_oper -eq 0 ] && show_help && exit

    mkdir -p dist

    if (($targets&a));then
        genDistForProject admin admin
    fi

    if (($targets&s));then
        genDistForProject server server
    fi
}

main "$@"
