#!/bin/bash

proj="ghwgh"
distpath="../../../CardNodeServer/tools/dist/${proj}"
remoteUrl="http://120.25.96.74:3000/${proj}/app"

function genIOSBundle() {
    react-native bundle \
        --platform ios \
        --reset-cache \
        --verbose \
        --entry-file index.ios.js \
        --bundle-output ./tools/www/index.ios.bundle \
        --assets-dest ./tools/www/ \
        --dev false
}

function genAndroidBundle() {
    react-native bundle \
        --platform android \
        --reset-cache \
        --verbose \
        --entry-file index.android.js \
        --bundle-output ./tools/www/index.android.bundle \
        --assets-dest ./tools/www/ \
        --dev false
}

function zipWWW() {
    node -e "!function(){function i(e,r){var o=n.readdirSync(e);o.forEach(function(o){var s=e+'/'+o;n.statSync(s).isDirectory()?i(s,r+'/'+o):c.folder(r).file(o,n.readFileSync(s))})}function e(e,r,o){r=r||'',o=o||e+'.zip',i(e,r);var s=c.generate({base64:!1,compression:'DEFLATE'});n.writeFile(o,s,'binary',function(){console.log('success')})}var r=require('jszip'),n=require('fs'),c=new r,o=process.argv.splice(1);e.apply(null,o)}();"  www${1} _www www${1}.zip
}

function genMd5List() {
    node -e "var o=process.argv;require('./getMd5List')(o[1],o[2])" ${1} "${remoteUrl}/${1}_md5.json"
}

function zipFile() {
    zipWWW
    mv ./www.zip ${distpath}/js${1}.zip
    rm -fr www
    echo [] > www_all/needCopyFiles.json
    zipWWW _all
    mv ./www_all.zip ${distpath}/js${1}_all.zip
    rm -fr www_all
    mv ./${1}_md5.json ${distpath}/${1}_md5.json
    echo "${distpath}"
}

function buildAndroid() {
    rm -fr www
    mkdir www
    pushd ..
    genAndroidBundle
    popd
    cp -r www www_all
    genMd5List android
    zipFile android
}

function buildIos() {
    rm -fr www
    mkdir www
    pushd ..
    genIOSBundle
    popd
    cp -r www www_all
    genMd5List ios
    zipFile ios
}

function main() {
    if [ "$1" = "android" ];then
        buildAndroid
    elif [ "$1" = "ios" ];then
        buildIos
    elif [ "$1" = "all" ];then
        buildAndroid
        buildIos
    else
        echo "Usage: ./genbundle ios|android|all"
    fi
}

main $@
