#!/bin/bash

src="${1-./img/splash.png}"

ffmpeg -i ${src} -s 640x1136 ../ios/GHwgh/splash/Default-568h@2x~iphone.png -y
ffmpeg -i ${src} -s 750x1334 ../ios/GHwgh/splash/Default-667h.png -y
ffmpeg -i ${src} -s 1242x2208 ../ios/GHwgh/splash/Default-736h.png -y
ffmpeg -i ${src} -s 640x960 ../ios/GHwgh/splash/Default@2x~iphone.png -y
ffmpeg -i ${src} -s 320x480 ../ios/GHwgh/splash/Default~iphone.png -y
ffmpeg -i ${src} -s 320x568 ../ios/GHwgh/splash/splash.png -y
mkdir -p ../android/app/src/main/res/drawable
cp ../ios/GHwgh/splash/splash.png ../android/app/src/main/res/drawable/splash.png
